{
 "title": "[infrastructure] host resource usage overview",
 "tags": [ "infrastructure" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "${server}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server",
   "targets": [
    {}
   ]
  },
  {
   "title": "Systemd Units State",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_units{host=\"$server\",job=\"node\",state=\"activating\"}",
     "legendFormat": "Activating"
    },
    {
     "expr": "node_systemd_units{host=\"$server\",job=\"node\",state=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_systemd_units{host=\"$server\",job=\"node\",state=\"deactivating\"}",
     "legendFormat": "Deactivating"
    },
    {
     "expr": "node_systemd_units{host=\"$server\",job=\"node\",state=\"failed\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "node_systemd_units{host=\"$server\",job=\"node\",state=\"inactive\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{host=\"$server\",job=\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',host=\"$server\",job=\"node\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{host=\"$server\",job=\"node\"}) by (cpu))",
     "legendFormat": "$server"
    }
   ]
  },
  {
   "title": "Diskspace used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",host=\"$server\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",host=\"$server\"})",
     "legendFormat": "mount {{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/data\",host=\"$server\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/data\",host=\"$server\"})",
     "legendFormat": "mount {{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{host=\"$server\"} - node_memory_MemFree_bytes{host=\"$server\"} - (node_memory_Cached_bytes{host=\"$server\"} + node_memory_Buffers_bytes{host=\"$server\"})) / node_memory_MemTotal_bytes{host=\"$server\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Systemd Units State",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{host=\"$server\", name=~\".+.service\", type=\"simple\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hours since last timer trigger",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_systemd_timer_last_trigger_seconds{job=\"node\", host=\"$server\"}",
     "legendFormat": "{{alias}}: {{name}}"
    }
   ]
  }
 ]
}