
name: Deploy module docs to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  pages: write
  # needed by actions/deploy-pages
  id-token: write

jobs:
  docs:
    name: Generate and deploy docs 
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false
          extra-conf: |
            extra-substituters = https://b10c-nixpkgs.cachix.org
            extra-trusted-public-keys = b10c-nixpkgs.cachix.org-1:okaPyE6H0JAJb4H1J8r7mnf7Gst+0c6Djz7ff3QDGkY=

      - name: Configure Pages
        uses: actions/configure-pages@v6

      - name: Show Nix version
        run: nix --version

      - name: Build docs
        run: nix build .#docs --print-build-logs --show-trace

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'result/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
